### ISSUE TITLE
Plugin not found on npm or yarn

### ISSUE THREAD

**Issue by webtwitter** [NoriSte/gatsby-plugin-perfume.js#101]
Hello, it seems like this plugin is not on npm or yarn

``[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/gatsby-plugin-perfume: Not found".``

**Comment by NoriSte** [comment]
My fault! The plugin is in the registry as `gatsby-plugin-perfume*.js*`, not `gatsby-plugin-perfume` as I wrote in the readme! Sorry, tomorrow I'll fix it!

https://www.npmjs.com/package/gatsby-plugin-perfume.js

**Comment by NoriSte** [comment]
I've just fixed the name @webtwitter 😉

**Comment by webtwitter** [comment]
Thank you sir :)
