### ISSUE TITLE
Perfume.js v4.5.0 is out

### ISSUE THREAD

**Issue by Zizzamia** [NoriSte/gatsby-plugin-perfume.js#176]
Ciao @NoriSte, can you please update the plugin to the latest Perfume version.
Also, we should have a section in the main Perfume [README](https://github.com/Zizzamia/perfume.js/blob/master/README.md) for external plugins, would you mind open a PR and create a section for it?

**Comment by NoriSte** [comment]
All done in December, I forgot to close this issue 😊
